services:
  db:
    image: mysql:8.0 # MySQL 8.0 이미지 사용
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: tnm
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306" # 호스트의 3306 포트를 컨테이너로 매핑
    volumes:
      - ./db_data:/var/lib/mysql # MySQL 데이터를 호스트에 저장
