# Generated by Django 5.1.4 on 2025-01-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_account_category_categorydetail_monthly_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateField(),
        ),
    ]
